# -*- coding: utf-8 -*-
"""diabities_Data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qotn1cNWxpr0J_NnSbwgvn8fSt4iOHH1
"""

import pandas as pd

df = pd.read_csv("/content/diabetes.csv")

"""**Explore The DataSet**"""

# To see the top 5 rows of the dataset
df.head()

#To see the below 5 rows
df.tail()

df.tail(2)

#see the size of rows and colomns ,i.e shape of the dataset
df.shape

# to see the Names of the colomns
df.columns

#Data Types of Colomns name?
df.dtypes

#general spesifications of data sets / summary
df.info()

#statistical Summary of dataset
df.describe()

"""**To check the data Quality**"""

#check the missing value
df.isnull()

df.isnull().count()

#check the duplicate Values
df.duplicated().sum()

#To count uniqe values per coloumn
df.nunique()

#check the invalid zero Values(real Missing data)
(df[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']] == 0).sum()

"""**Selecting The Data & Filtering the Data**"""

#selecting the column
df['BloodPressure']

#Multiple column
df[['Age' , 'BloodPressure']]

#filter rows by some condition
df[df['Age']>60]

df[df['Age']>60].count()

#Filter With multiple Conditions
df[(df['Age']>65 )& (df['Outcome'] == 1)]

#access rows by index
df.iloc[700:710]

"""**Sorting and Grouping**"""

#sort by using column
df.sort_values(by='Age')

#Value Count
df['Outcome'].value_counts()

df['Glucose'].value_counts()

#Group by and aggregate the Data
df.groupby('Outcome').mean()

#Statistics
#Mean of a column


df['BMI'].mean()

#Median
#df['Glucose'].median()
df['BMI'].median()

#Standerd Devietion
df['Age'].std()

#Coorelation Matrix
df.corr()

"""**ModiFication of the Data**"""

#add a new coloumn
df['BMI_CATEGORY'] = pd.cut(df['BMI'] , bins=[0,18.5,24.9,29.9,100],labels = ['Underweight' , 'Normal' , 'Overweight' , 'Obese'])

df.head(20)

#replace invalid zero
df['Insulin'] = df['Insulin'].replace(0,df['Insulin'].mean())

df.head(20)

"""**Data visualisation**"""

#Histogram
import matplotlib.pyplot as plt
import seaborn as sns

plt.hist(df['Age'])
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.title('Age Distribution')
plt.show()

